#!/bin/bash

echo "🚀 Backend Deployment Guide for Render"
echo "======================================"
echo ""
echo "Follow these steps on dashboard.render.com:"
echo ""
echo "1️⃣  CREATE DATABASE:"
echo "   • Click 'New +' → 'PostgreSQL'"
echo "   • Name: gymsite-db"
echo "   • Database: gym_fitness"
echo "   • User: gymuser"
echo "   • Region: Oregon (US West)"
echo "   • Plan: Free"
echo "   • Click 'Create Database'"
echo "   • Wait 2-3 minutes"
echo "   • Copy the External Database URL"
echo ""
echo "2️⃣  DEPLOY BACKEND:"
echo "   • Click 'New +' → 'Web Service'"
echo "   • Connect GitHub: vivekkumar860/gymSite"
echo "   • Configure:"
echo "     - Name: gymsite-backend"
echo "     - Region: Oregon (same as DB)"
echo "     - Branch: main"
echo "     - Root Directory: backend"
echo "     - Runtime: Node"
echo "     - Build Command: npm install && npx prisma generate && npm run build"
echo "     - Start Command: npm run start:prod"
echo "     - Plan: Free"
echo ""
echo "3️⃣  ADD ENVIRONMENT VARIABLES:"
echo "   Click 'Environment' and add:"
echo ""
echo "NODE_ENV=production"
echo "PORT=3001"
echo "DATABASE_URL=[paste your PostgreSQL External URL here]"
echo "JWT_SECRET=$(openssl rand -base64 32)"
echo "JWT_EXPIRES_IN=15m"
echo "REFRESH_TOKEN_SECRET=$(openssl rand -base64 32)"
echo "CORS_ORIGIN=https://gymplannerworkout.netlify.app"
echo ""
echo "4️⃣  DEPLOY:"
echo "   • Click 'Create Web Service'"
echo "   • Wait 5-10 minutes for deployment"
echo "   • Your backend URL: https://gymsite-backend.onrender.com"
echo ""
echo "5️⃣  INITIALIZE DATABASE (after deployment):"
echo "   • Go to Service → 'Shell' tab"
echo "   • Run: npx prisma migrate deploy"
echo "   • Run: npm run prisma:seed (optional - adds sample data)"
echo ""
echo "Press Enter to continue once you've completed these steps..."
read -p ""

echo ""
echo "Testing backend health..."
curl -s https://gymsite-backend.onrender.com/health || echo "Backend not ready yet. It may take a few minutes to deploy."