[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "https://gymsite-backend.onrender.com/api/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_BASE_URL = "https://gymsite-backend.onrender.com"
  NEXT_PUBLIC_APP_NAME = "GymPlanner Workout"
  NEXT_PUBLIC_APP_URL = "https://gymplannerworkout.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"